const BOMB = -1;

const GAME_NOT_FOUND = "GAME_NOT_FOUND";
const ALREADY_MARKED = "ALREADY_MARKED";
const ALREADY_SHOOTED = "ALREADY_SHOOTED";
const ALREADY_PLAYING = "ALREADY_PLAYING";
const NOT_YOUR_TURN = "NOT_YOUR_TURN";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const NAME_REQUIRED = "NAME_REQUIRED";
const FIELD_ERROR = "FIELD_ERROR";

const END_GAME = "END_GAME";

module.exports = {
  BOMB: BOMB,
  GAME_NOT_FOUND: GAME_NOT_FOUND,
  ALREADY_MARKED: ALREADY_MARKED,
  ALREADY_SHOOTED: ALREADY_SHOOTED,
  ALREADY_PLAYING: ALREADY_PLAYING,
  NOT_YOUR_TURN: NOT_YOUR_TURN,
  USER_NOT_FOUND: USER_NOT_FOUND,
  NAME_REQUIRED: NAME_REQUIRED,
  FIELD_ERROR: FIELD_ERROR,
  END_GAME: END_GAME
};